name: Periodically update the response codes for the services

on:
  schedule:
    - cron: 5 * * * *

jobs:
  http-resp:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - name: Install the dependency packages
        working-directory: /
        run: |
             sudo dnf install curl git --setopt=install_weak_deps=False --assumeyes
      - name: Configure Git before starting off with any Git related operations
        working-directory: /__w/gostatus
        run: |
             git config --global --add safe.directory $(realpath .)
             git config --global user.email ${{ secrets.USERMAIL }}
             git config --global user.name ${{ secrets.USERNAME }}
      - name: Clone the status worker repository in its current state
        working-directory: /__w/gostatus
        run: |
             git clone https://${{ secrets.GTHBUSER }}:${{ secrets.GHBTOKEN }}@github.com/t0xic0der/gostatus.git goworker
      - name: Clone the status report repository in its current state
        working-directory: /__w/gostatus
        run: |
             git clone https://${{ secrets.GTLBUSER }}:${{ secrets.GLBTOKEN }}@gitlab.com/t0xic0der/gostatus.git goreport
      - name: Generate a status record of response codes for the services
        working-directory: /__w/gostatus/goworker
        run: |
             sh test/http-resp.sh
      - name: Pull the most recently made changes from the status worker repository before moving in the modified files
        working-directory: /__w/gostatus/goreport
        run: |
             git pull origin main
      - name: Copy over the modified files to the directory containing the local status report repository
        working-directory: /__w/gostatus/goreport
        run: |
             mv /var/tmp/resp/* resp/
      - name: Commit the changes to the local repository
        working-directory: /__w/gostatus/goreport
        run: |
             git add resp/
             git commit -sm "$(date +%Y%m%d-%H%M%Z): Update status record for response codes"
      - name: Push the new changes to the remote repository
        working-directory: /__w/gostatus/goreport
        run: |
             git push origin main
